// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pomwxwpontzwzdhgrjmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvbXd4d3BvbnR6d3pkaGdyam1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTU3MzIsImV4cCI6MjA2MDc5MTczMn0.6JfZfc19OfToyU7wGLNl7UQBLfp26gg86iLylzE5NaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);